name: Application demo image artifacts

on:
  push:
    branches: [master]

jobs:
  backbone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: defconfig
        run: make demo_backbone_defconfig
      - name: build
        run: make
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-demo-backbone-coronet
          path: output/images/*
  dhcp-boot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: defconfig
        run: make demo_dhcp_boot_defconfig
      - name: build
        run: make
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: app-demo-dhcp-boot-coronet
          path: output/images/*
